[package]
name = "rustonic_desktop"
version = "0.1.0"
edition = "2024"

[dependencies]
slint = "1.14.1"
rustonic_shared = { path = "../rustonic_shared" }
md5 = "0.8.0"
async-compat = "0.2.5"

[build-dependencies]
slint-build = "1.14.1"
