[package]
name = "rustonic_desktop"
version = "0.1.0"
edition = "2024"

[dependencies]
slint = "1.14.1"
rustonic_shared = { path = "../rustonic_shared" }
md5 = "0.8.0"
tokio = { version = "1.48.0", features = ["full"] }

[build-dependencies]
slint-build = "1.14.1"
